### ISSUE TITLE
Example data

### ISSUE THREAD

**Issue by hguan6** [ModelarData/ModelarDB-RS#132]
I want to quickly get started with ModelarDB but don't know how to prepare the data. The user document only talks about putting data in a local folder or a cloud but doesn't mention what type of data files to put. Can you give me an example of such a data file? If there are multiple data files in the folder, are they supposed to be data from multiple data source? Thank you!

**Comment by CGodiksen** [comment]
Hello and thank you for showing interest in ModelarDB.

ModelarDB works by ingesting data through the `do_put` Apache Arrow Flight endpoint. This data is then compressed using model-based compression and saved in either a local folder or in the cloud, depending on how you started the ModelarDB server. For more information on ingesting data you can have a look at the [Ingest Data](https://github.com/ModelarData/ModelarDB-RS/blob/master/docs/user/README.md#ingest-data) part of the [user documentation](https://github.com/ModelarData/ModelarDB-RS/tree/master/docs/user). 

If you have created a model table for the data, you can also ingest entire Apache Parquet files into ModelarDB from Python using the following code example:
```python
from pyarrow import parquet
from pyarrow import flight

flight_client = flight.FlightClient("grpc://127.0.0.1:9999")
arrow_table = parquet.read_table(path)

upload_descriptor = flight.FlightDescriptor.for_path(table_name)
writer, _ = flight_client.do_put(upload_descriptor, arrow_table.schema)
writer.write(arrow_table)
writer.close()
```

The above example uses Apache Parquet, but you can also ingest many other types of files such as [CSV](https://arrow.apache.org/docs/python/csv.html) and [JSON](https://arrow.apache.org/docs/python/json.html). 

Since ModelarDB converts the data into files with a ModelarDB specific format, you need to use the `do_get` Apache Arrow Flight endpoint to retrieve the data you have ingested. For more information on how to query your data you can have a look at the [Execute SQL](https://github.com/ModelarData/ModelarDB-RS/tree/master/docs/user#execute-sql) part of the [user documentation](https://github.com/ModelarData/ModelarDB-RS/tree/master/docs/user). 

It should be noted that we are still in early development but we are planning on focusing more on documentation and other features such as a Python library to make ModelarDB easier to use in the future. Again, thank you for your interest.

**Comment by hguan6** [comment]
Thank you very much for the explanation!
